---
title: Modern Web Tutorials
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title.html"
url: https://blog.buzzlor.com
full_name: Ahmed Bouchefra
first_name: Ahmed
last_name: ''
blog_title: Home of Modern Web Tutorials
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: techiediaries
copyright_year: '2018'
google_analytics_code: ''
aboutme: A web developer, technical author and consultant.
twitter: ahmedbouchefra
github: techiediaries
facebook: techiediaries
linkined_url: ''
