---
title: Home of Django Tutorials
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title.html"
url: https://blog.buzzlor.com
full_name: Abbes
first_name: Abbes
last_name: ''
blog_title: Home of Django Tutorials
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: buzzlor
copyright_year: '2017'
google_analytics_code: ''
aboutme: I'm a developer and web entrepreneur
twitter: buzzlor
github: buzzlor
facebook: buzzlor
linkined_url: ''
