
permalink: /:categories/:title.html
url: "https://techiediaries.github.io"
full_name: "Ahmed Bouchefra"
first_name: "Ahmed"
last_name: ""
blog_title: "Techiediaries"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "techiediaries"
copyright_year: "2017"
google_analytics_code: ""
aboutme: "I'm a developer and web entrepreneur"
twitter: "techiediaries"
github: "techiediaries"
facebook: "ahmed.bouchefra"
linkined_url: ""
